### ISSUE TITLE
Certain text files have been crashing analyzer and recalc

### ISSUE THREAD

**Issue by gp2856** [kaegi/MorphMan#110]
I have been trying to import a large amount of cards from a text file containing all lines of dialogue from a game.  Importing them works without any issues, but when I recalc I get a stacktrace error.  I attempted to try and isolate whatever fragment was causing the issue, but after splitting the first half of the file 9 times I still could not find any line in particular that was causing this issue.  After I had split the data down to a significant amount, I tried to delete the line mentioned in the stacktrace one-by-one to see if I could find a specific line that was causing the problem.  I have not been able to isolate this.
I've uploaded the text I'm trying to import here:  https://gist.github.com/gp2856/67c00a9938add09c156ce95cffc0136f

Stack trace from recalc here:
```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-06 15:17:35

Caught exception:
Traceback (most recent call last):
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ('オホン。聞こえてないのかな…あけ―',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ('オホン。聞こえてないのかな…あけ―',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\__init__.py", line 14, in onMorphManRecalc
    main.main()
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\main.py", line 430, in main
    allDb = mkAllDb(cur)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\main.py", line 126, in mkAllDb
    ms = getMorphemes(morphemizer, fieldValue, ts)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\morphemes.py", line 165, in getMorphemes
    ms = morphemizer.getMorphemesFromExpr(expression)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\morphemizer.py", line 68, in getMorphemesFromExpr
    return getMorphemesMecab(expression)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 43, in __call__
    value = self.func(*args)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 88, in getMorphemesMecab
    ms = [getMorpheme(m.split('\t')) for m in interact(e).split('\r')]
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 43, in __call__
    value = self.func(*args)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 235, in interact
    p.stdin.flush()
OSError: [Errno 22] Invalid argument
```

from analyzer here:
```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-06 15:17:35

Caught exception:
Traceback (most recent call last):
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ('"ちょっと、フォア。ガビィから離れなさい。#眠らせてあげて。"\n',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ('"ちょっと、フォア。ガビィから離れなさい。#眠らせてあげて。"\n',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\readability.py", line 137, in <lambda>
    self.ui.analyzeButton.clicked.connect(lambda le: self.onAnalyze())
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\readability.py", line 409, in onAnalyze
    measure_readability(file_path, is_ass, is_srt)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\readability.py", line 353, in measure_readability
    proc_lines(input, is_ass, is_srt)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\readability.py", line 343, in proc_lines
    parse_text(filtered_text)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\readability.py", line 278, in parse_text
    parsed_morphs = getMorphemes(morphemizer, stripHTML(text))
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\morphemes.py", line 165, in getMorphemes
    ms = morphemizer.getMorphemesFromExpr(expression)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\morphemizer.py", line 68, in getMorphemesFromExpr
    return getMorphemesMecab(expression)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 43, in __call__
    value = self.func(*args)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 88, in getMorphemesMecab
    ms = [getMorpheme(m.split('\t')) for m in interact(e).split('\r')]
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 43, in __call__
    value = self.func(*args)
  File "C:\Users\GP\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 235, in interact
    p.stdin.flush()
OSError: [Errno 22] Invalid argument
```

**Comment by gp2856** [comment]
I have also tried saving this file as a csv and importing from that with the same issue.

**Comment by Okkun9001** [comment]
I'm having the same problem. Did you figure out a solution to this? Or can anyone else help with this?
