### ISSUE TITLE
Anki 2.1.26 Error's on Start

### ISSUE THREAD

**Issue by 0lliee** [kaegi/MorphMan#122]
Just got a new computer and installed Anki with Japanese Support Addon and Morphman and as soon as I open Anki these two errors appear:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-15 00:06:00

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 43, in handler
  File "aqt\main.py", line 671, in reset
  File "aqt\main.py", line 632, in moveToState
  File "aqt\main.py", line 639, in _deckBrowserState
  File "aqt\deckbrowser.py", line 56, in show
  File "aqt\toolbar.py", line 48, in draw
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-2>", line 2, in _centerLinks
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 635, in repl
  File "C:\Users\boult\AppData\Roaming\Anki2\addons21\900801631\morph\stats.py", line 73, in my_centerLinks
    return self._linkHTML(links)
AttributeError: 'Toolbar' object has no attribute '_linkHTML'

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-15 00:06:00

Traceback (most recent call last):
  File "aqt\main.py", line 497, in loadCollection
  File "aqt\main.py", line 632, in moveToState
  File "aqt\main.py", line 639, in _deckBrowserState
  File "aqt\deckbrowser.py", line 56, in show
  File "aqt\toolbar.py", line 48, in draw
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-2>", line 2, in _centerLinks
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 635, in repl
  File "C:\Users\boult\AppData\Roaming\Anki2\addons21\900801631\morph\stats.py", line 73, in my_centerLinks
    return self._linkHTML(links)
AttributeError: 'Toolbar' object has no attribute '_linkHTML'
Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 43, in handler
  File "aqt\main.py", line 162, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 199, in setupProfile
  File "aqt\main.py", line 398, in loadProfile
  File "aqt\gui_hooks.py", line 1559, in __call__
  File "lib\site-packages\anki\hooks.py", line 583, in runHook
  File "C:\Users\boult\AppData\Roaming\Anki2\addons21\900801631\morph\preferences.py", line 7, in init_preferences
    _init_config_py()
  File "C:\Users\boult\AppData\Roaming\Anki2\addons21\900801631\morph\preferences.py", line 35, in _init_config_py
    mw.toolbar.draw()
  File "aqt\toolbar.py", line 48, in draw
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-2>", line 2, in _centerLinks
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 635, in repl
  File "C:\Users\boult\AppData\Roaming\Anki2\addons21\900801631\morph\stats.py", line 73, in my_centerLinks
    return self._linkHTML(links)
AttributeError: 'Toolbar' object has no attribute '_linkHTML'

**Comment by 0lliee** [comment]
Updating the stats.py with the code from here: https://github.com/kaegi/MorphMan/blob/master/morph/stats.py seems to fix it. Should've read the Anki comments first!
