### ISSUE TITLE
Anki 2.1.26, Morphman Preferences not getting saved

### ISSUE THREAD

**Issue by fqrious** [kaegi/MorphMan#124]
When I save the preference, it shows a toast ```please recalculate your database to avoid unexpected behaviour``` but when I recalculate my database there is no visible difference. Also, when I go back into preferences the setting will be back to default.

**Comment by yaoberh** [comment]
Same problem here.

**Comment by sb7297** [comment]
What version of MorphMan are you using?

**Comment by yaoberh** [comment]
The one from ankiweb. Also tried replacing the stats.py suggested in the comments. Also tried using the version from here. None work.

**Comment by fqrious** [comment]
I'm also using the one from ankiweb, however after checking morph/__init__.py, I found out that it's v3.6

**Comment by fqrious** [comment]
@yaoberh you can download preferences.py from [here](https://github.com/fqrious/MorphMan/blob/patch-1/morph/preferences.py) to replace your morph/preferences.py for now

**Comment by yaoberh** [comment]
When I replace the preferences.py file I get a startup error.
When loading '⁨MorphMan for Anki 21⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/__init__.py", line 1, in <module>
    from .morph.util import *
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util.py", line 12, in <module>
    from .preferences import get_preference, init_preferences
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/preferences.py", line 6
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by sb7297** [comment]
@yaoberh You need to download the raw file. Use [this link](https://raw.githubusercontent.com/fqrious/MorphMan/patch-1/morph/preferences.py).

**Comment by yaoberh** [comment]
Yep, seems to be working now. Although me being on Manjaro x64 linux I now get a mecab-ipadic error. They are installed, but nevertheless it's not working...

**Comment by joestrong** [comment]
Upon investigation, I think Anki 2.1.24 broke it. See the comment at the top of https://github.com/ankitects/anki/blob/2.1.24/pylib/anki/config.py for details

#127 does indeed fix it, but I think we should update to Anki's suggested ConfigManager methods. I've mentioned this on the PR too
