### ISSUE TITLE
Not able to recalc in Manjaro x64

### ISSUE THREAD

**Issue by yaoberh** [kaegi/MorphMan#129]
So I installed Mecab and Mecab ipadic like suggested in the install wiki, but when I recalc I get this error:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.28 (97eadb78) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-21 12:26:23
Add-ons possibly involved: ⁨MorphMan for Anki 21⁩

Caught exception:
Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ('イニシアチブ',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ('イニシアチブ',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/__init__.py", line 14, in onMorphManRecalc
    main.main()
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/main.py", line 430, in main
    allDb = mkAllDb(cur)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/main.py", line 126, in mkAllDb
    ms = getMorphemes(morphemizer, fieldValue, ts)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/morphemes.py", line 165, in getMorphemes
    ms = morphemizer.getMorphemesFromExpr(expression)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/morphemizer.py", line 68, in getMorphemesFromExpr
    return getMorphemesMecab(expression)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 43, in __call__
    value = self.func(*args)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/mecab_wrapper.py", line 86, in getMorphemesMecab
    ms = [getMorpheme(m.split('\t')) for m in interact(e).split('\r')]
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 43, in __call__
    value = self.func(*args)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/mecab_wrapper.py", line 220, in interact
    p, _ = mecab()
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 43, in __call__
    value = self.func(*args)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/mecab_wrapper.py", line 213, in mecab
    return spawnMecab(m.mecabCmd[:1] + m.mecabCmd[4:], si), mecab_source
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/mecab_wrapper.py", line 118, in spawnMecab
    raise OSError(
OSError: Unexpected MeCab dictionary format; unidic or ipadic required.
Try installing the 'Mecab Unidic' or 'Japanese Support' addons,
or if using your system's `mecab` try installing a package
like `mecab-ipadic`

**Comment by sb7297** [comment]
Have you tried using Japanese Support?

**Comment by yaoberh** [comment]
Yes, I just tried and it gave me this error:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.28 (97eadb78) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-21 12:26:23
Add-ons possibly involved: ⁨MorphMan for Anki 21⁩

Caught exception:
Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/__init__.py", line 14, in onMorphManRecalc
    main.main()
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/main.py", line 447, in main
    knownDb = updateNotes(allDb)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/main.py", line 289, in updateNotes
    focusMorphIndex = frequency_list[focusMorphString]
TypeError: list indices must be integers or slices, not str

**Comment by sb7297** [comment]
Try using [this version](https://raw.githubusercontent.com/SaraSmiseth/MorphMan/fix_frequency_list_init/morph/main.py) of morph/main.py, from @SaraSmiseth's PR.

**Comment by yaoberh** [comment]
Working now! Thanks a lot :)
