### ISSUE TITLE
Unable to see new cards. Manjaro x64

### ISSUE THREAD

**Issue by yaoberh** [kaegi/MorphMan#130]
Whenever I try to see new cards an error appears. Sometimes I'm allowed to see the front of the card but not the back but almost always it won't even let me see that. Reviews are fine and don't show any errors whatsoever.
This is the error:
Anki 2.1.28 (97eadb78) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-21 12:26:23
アドオンが関連している可能性があります：⁨MorphMan for Anki 21, Web Browser - Search terms Import texts and images automatically, Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 34, in cmd
  File "aqt/webview.py", line 114, in _onCmd
  File "aqt/webview.py", line 518, in _onBridgeCmd
  File "</usr/local/share/anki/bin/decorator.pyc:decorator-gen-34>", line 2, in _linkHandler
  File "anki/hooks.py", line 614, in decorator_wrapper
  File "anki/hooks.py", line 611, in repl
  File "/home/yaoberh/.local/share/Anki2/addons21/review_heatmap/links.py", line 69, in heatmapLinkHandler
    return None if not _old else _old(self, url)
  File "aqt/overview.py", line 67, in _linkHandler
  File "aqt/main.py", line 635, in moveToState
  File "aqt/main.py", line 657, in _reviewState
  File "aqt/reviewer.py", line 65, in show
  File "/home/yaoberh/.local/share/Anki2/addons21/864545277/review_controller.py", line 97, in wrapped
    originalResult = originalFunction(self)
  File "aqt/reviewer.py", line 110, in nextCard
  File "anki/schedv2.py", line 52, in getCard
  File "anki/schedv2.py", line 237, in _getCard
  File "</usr/local/share/anki/bin/decorator.pyc:decorator-gen-24>", line 2, in _getNewCard
  File "anki/hooks.py", line 614, in decorator_wrapper
  File "anki/hooks.py", line 611, in repl
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/newMorphHelper.py", line 98, in my_getNewCard
    card = _old(self)  # type: anki.cards.Card
  File "anki/schedv2.py", line 307, in _getNewCard
  File "</usr/local/share/anki/bin/decorator.pyc:decorator-gen-20>", line 2, in _fillNew
  File "anki/hooks.py", line 614, in decorator_wrapper
  File "anki/hooks.py", line 611, in repl
TypeError: my_fillNew() got multiple values for argument '_old'

**Comment by yaoberh** [comment]
Disabling Review Heatmap and Web Browser as suggested to be possible culprits doesn't seem to solve the problem. I get this error:
Anki 2.1.28 (97eadb78) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-21 12:26:23
アドオンが関連している可能性があります：⁨MorphMan for Anki 21⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 34, in cmd
  File "aqt/webview.py", line 114, in _onCmd
  File "aqt/webview.py", line 518, in _onBridgeCmd
  File "aqt/overview.py", line 67, in _linkHandler
  File "aqt/main.py", line 635, in moveToState
  File "aqt/main.py", line 657, in _reviewState
  File "aqt/reviewer.py", line 65, in show
  File "aqt/reviewer.py", line 110, in nextCard
  File "anki/schedv2.py", line 52, in getCard
  File "anki/schedv2.py", line 237, in _getCard
  File "</usr/local/share/anki/bin/decorator.pyc:decorator-gen-24>", line 2, in _getNewCard
  File "anki/hooks.py", line 614, in decorator_wrapper
  File "anki/hooks.py", line 611, in repl
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/newMorphHelper.py", line 98, in my_getNewCard
    card = _old(self)  # type: anki.cards.Card
  File "anki/schedv2.py", line 307, in _getNewCard
  File "</usr/local/share/anki/bin/decorator.pyc:decorator-gen-20>", line 2, in _fillNew
  File "anki/hooks.py", line 614, in decorator_wrapper
  File "anki/hooks.py", line 611, in repl
TypeError: my_fillNew() got multiple values for argument '_old'

**Comment by sourstripe** [comment]
Same issue except I'm on windows
