### ISSUE TITLE
Recalculation error on 2.1.26

### ISSUE THREAD

**Issue by edoreld** [kaegi/MorphMan#139]
An error pops up at the end of the recalculation process.

```Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-06-11 21:32:27
Add-ons possibly involved: ⁨MorphMan for Anki 21⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/jmartinezlago/Library/Application Support/Anki2/addons21/900801631/__init__.py", line 14, in onMorphManRecalc
    main.main()
  File "/Users/jmartinezlago/Library/Application Support/Anki2/addons21/900801631/morph/main.py", line 443, in main
    knownDb = updateNotes(allDb)
  File "/Users/jmartinezlago/Library/Application Support/Anki2/addons21/900801631/morph/main.py", line 395, in updateNotes
    mw.col.db.executemany(
  File "anki/dbproxy.py", line 92, in executemany
  File "anki/rsbackend.py", line 459, in db_execute_many
  File "anki/rsbackend.py", line 471, in _db_command
ankirspy.DBError: JSONError { info: "invalid type: map, expected a sequence" }
```

**Comment by edoreld** [comment]
Resolved after updating my main.py file as [explained here](https://github.com/kaegi/MorphMan/issues/133#issuecomment-636275260)
