### ISSUE TITLE
mecab-ipadic problem - Arch linux

### ISSUE THREAD

**Issue by yaoberh** [kaegi/MorphMan#142]
After "prep work for all.db creation" appears, I get this error. I'm running Manjaro x64.
Any suggestions? Installing mecab-ipadic doesn't work.

Caught exception:
Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ('大阪弁',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ('大阪弁',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/__init__.py", line 14, in onMorphManRecalc
    main.main()
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/main.py", line 434, in main
    allDb = mkAllDb(cur)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/main.py", line 128, in mkAllDb
    ms = getMorphemes(morphemizer, fieldValue, ts)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/morphemes.py", line 165, in getMorphemes
    ms = morphemizer.getMorphemesFromExpr(expression)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/morphemizer.py", line 68, in getMorphemesFromExpr
    return getMorphemesMecab(expression)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 43, in __call__
    value = self.func(*args)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/mecab_wrapper.py", line 86, in getMorphemesMecab
    ms = [getMorpheme(m.split('\t')) for m in interact(e).split('\r')]
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 43, in __call__
    value = self.func(*args)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/mecab_wrapper.py", line 220, in interact
    p, _ = mecab()
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/util_external.py", line 43, in __call__
    value = self.func(*args)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/mecab_wrapper.py", line 213, in mecab
    return spawnMecab(m.mecabCmd[:1] + m.mecabCmd[4:], si), mecab_source
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/mecab_wrapper.py", line 118, in spawnMecab
    raise OSError(
OSError: Unexpected MeCab dictionary format; unidic or ipadic required.
Try installing the 'Mecab Unidic' or 'Japanese Support' addons,
or if using your system's `mecab` try installing a package
like `mecab-ipadic`

**Comment by nicolas0p** [comment]
Can anyone confirm this is related to the issue fixed by the edits suggested in this reddit comment?

https://www.reddit.com/r/LearnJapanese/comments/g8ngtm/how_did_you_guys_update_your_mecab_unidic/fow4xto/
