### ISSUE TITLE
TypeError: list indices must be integers or slices, not strings

### ISSUE THREAD

**Issue by yaoberh** [kaegi/MorphMan#147]
Getting this error when doing recalc running Linux:

Caught exception:
Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/__init__.py", line 14, in onMorphManRecalc
    main.main()
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/main.py", line 447, in main
    knownDb = updateNotes(allDb)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/main.py", line 289, in updateNotes
    focusMorphIndex = frequency_list[focusMorphString]
TypeError: list indices must be integers or slices, not str

**Comment by SaraSmiseth** [comment]
The same as #123. PR #125 will fix it.
