### ISSUE TITLE
Recalc error

### ISSUE THREAD

**Issue by yaoberh** [kaegi/MorphMan#150]
Caught exception:
Traceback (most recent call last):
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/__init__.py", line 14, in onMorphManRecalc
    main.main()
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/main.py", line 443, in main
    knownDb = updateNotes(allDb)
  File "/home/yaoberh/.local/share/Anki2/addons21/900801631/morph/main.py", line 395, in updateNotes
    mw.col.db.executemany(
  File "anki/dbproxy.py", line 93, in executemany
  File "anki/rsbackend.py", line 224, in db_execute_many
  File "anki/rsbackend.py", line 242, in _db_command
anki.rsbackend.StringError: JSONError { info: "invalid type: map, expected a sequence" }

**Comment by MichalMichalak** [comment]
This solves it: https://github.com/kaegi/MorphMan/issues/133#issuecomment-636299262

**Comment by landonepps** [comment]
I just updated the version on AnkiWeb, so it should include the change.
