### ISSUE TITLE
Upgrade broke MeCab

### ISSUE THREAD

**Issue by NinKenDo64** [kaegi/MorphMan#27]
After upgrading to the latest version MeCab complains about format. this is true for the master a jieba branch. Returning it an earlier version fixes this issue.

Don't have time to see at which exact commit this breaks, but here is the error.

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morphman.py", line 6, in onMorphManRecalc
    morph.main.main()
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\main.py", line 321, in main
    allDb = mkAllDb( cur )
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\main.py", line 94, in mkAllDb
    ms = getMorphemes(morphemizer, fieldValue )
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\morphemes.py", line 59, in getMorphemes
    ms = morphemizer.getMorphemesFromExpr(expression)
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\morphemizer.py", line 51, in getMorphemesFromExpr
    return getMorphemesMecab(e)
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\util_external.py", line 15, in __call__
    value = self.func(*args)
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\morphemizer.py", line 66, in getMorphemesMecab
    ms = [ tuple( m.split('\t') ) for m in interact( e ).split('\r') ] # morphemes
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\util_external.py", line 15, in __call__
    value = self.func(*args)
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\morphemizer.py", line 132, in interact
    p = mecab()
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\util_external.py", line 15, in __call__
    value = self.func(*args)
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\morphemizer.py", line 127, in mecab
    return spawnMecab(m.mecabCmd[:1] + m.mecabCmd[4:], si)
  File "C:\Users\Amano Jack\AppData\Roaming\Anki2\addons\morph\morphemizer.py", line 95, in spawnMecab
    ''')
OSError: Unexpected MeCab dictionary format; ipadic required.

Try using the MeCab bundled with the Japanese Support addon,
or if using your system's `mecab` try installing a package
like `mecab-ipadic`.

**Comment by kaegi** [comment]
Should be fixed now. Thanks for reporting it!

**Comment by kaegi** [comment]
There are two issues which need to be addressed before I will accept it into the master branch:
 - jieba+dictionary is currently included inside `morph/deps`, which I don't like because it makes this repository unnecessarily big; a solution to this is a external "Japanese Support"-like plugin (MorphMan Chinese Support?) or maybe a git submodule
 - the `Check Database`-error when using posseg (does not hinder usage, but is very annoying and unsettling)

As soon as jieba is usable for you, I'm not doing further maintenance work on it (bug fixing and rebasing on latest versions), because the only real way to test the functionality currently is to use it in Anki - and I'm not learning Chinese right now. Because of the first point I might purge this branch from the future at some point in the future. So I suggest you do a fork, so this functionality doesn't disappear for you and so that you can rebase this branch on future versions.

**Comment by NinKenDo64** [comment]
Awesome thanks. Those are all good points. There's something weird going on that's preventing me from forking, but I'll fork it sometime over the coming week when I get a chance to figure out what the issue is,  then I'll see about fixing the problems you mentioned, and I'll see about moving it toward a module probably over my holidays in 2ish months time.

Thanks for all your help.
