### ISSUE TITLE
Broken test_preferences

### ISSUE THREAD

**Issue by shanrauf** [kaegi/MorphMan#77]
@davidgaya I think we broke this:
```
======================================================================
FAIL: test_dbsPath (test.test_preferences.TestPreferences)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\srauf\AppData\Roaming\Anki2\addons21\Morphman\test\test_preferences.py", line 35, in test_dbsPath
    self.assertPreference('path_dbs', 'somewhere/dbs')
  File "C:\Users\srauf\AppData\Roaming\Anki2\addons21\Morphman\test\test_preferences.py", line 20, in assertPreference
    return self.assertEqual(get_preference(name), value)
AssertionError: 'somewhere\\dbs' != 'somewhere/dbs'
- somewhere\dbs
?          ^
+ somewhere/dbs
?          ^
```

**Comment by shanrauf** [comment]
Nvm, #78 fixed it
