### ISSUE TITLE
Readibility Analyzer gives error

### ISSUE THREAD

**Issue by cholerwol** [kaegi/MorphMan#86]
Whenever I try to analyze a japanese text with the readibility analyzer, the following error appears:

Debug info:
Anki 2.1.19 (3c8690ae) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Manuel\AppData\Roaming\Anki2\addons21\900801631\morph\readability.py", line 120, in <lambda>
    self.ui.analyzeButton.clicked.connect(lambda le: self.onAnalyze())
  File "C:\Users\Manuel\AppData\Roaming\Anki2\addons21\900801631\morph\readability.py", line 303, in onAnalyze
    measure_readability(file_path, is_ass, is_srt)
  File "C:\Users\Manuel\AppData\Roaming\Anki2\addons21\900801631\morph\readability.py", line 267, in measure_readability
    input = '\n'.join([l.strip().replace(u'\ufeff', '') for l in f.readlines()])
  File "C:\python38\lib\codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 0: invalid start byte

-
What is the problem? I have no programming knowledge, I'd be glad if someone could help me.
Thanks in advance.

**Comment by ianki** [comment]
The file needs to be encoded in UTF-8 format.  An example of how to fix this on Windows is to open the file in Notepad and Save As, then select Encoding: UTF-8 in the Save As dialog.

**Comment by cholerwol** [comment]
> The file needs to be encoded in UTF-8 format. An example of how to fix this on Windows is to open the file in Notepad and Save As, then select Encoding: UTF-8 in the Save As dialog.

Thanks, that solved the problem.
