### ISSUE TITLE
Not working on anki 2.1.16

### ISSUE THREAD

**Issue by Geniusssmit** [kaegi/MorphMan#93]
Installed version from github. It's not working, what should I do? I have that issue on start

An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\main.py", line 186, in onOpenProfile
  File "<decorator-gen-32>", line 2, in loadProfile
  File "anki\hooks.py", line 74, in decorator_wrapper
  File "anki\hooks.py", line 69, in repl
  File "aqt\main.py", line 276, in loadProfile
  File "anki\hooks.py", line 29, in runHook
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan\morph\preferences.py", line 7, in init_preferences
    _init_config_py()
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan\morph\preferences.py", line 35, in _init_config_py
    mw.toolbar.draw()
  File "aqt\toolbar.py", line 26, in draw
  File "<decorator-gen-70>", line 2, in _centerLinks
  File "anki\hooks.py", line 74, in decorator_wrapper
  File "anki\hooks.py", line 71, in repl
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan\morph\stats.py", line 64, in my_centerLinks
    name, details = getStatsLink()
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan\morph\stats.py", line 51, in getStatsLink
    d = loadStats()
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan\morph\stats.py", line 19, in loadStats
    d = pickle.load(f)
<class 'ValueError'>: unsupported pickle protocol: 5

**Comment by Geniusssmit** [comment]
On second anki profile I have that issue.
![image](https://user-images.githubusercontent.com/24941285/74841590-f82a8980-5339-11ea-9e0d-942bbe02a88f.png)


Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.16 (4bc33e2f) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
Traceback (most recent call last):
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan-master\__init__.py", line 34, in onMorphManPreferences
    preferencesDialog.main()
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan-master\morph\preferencesDialog.py", line 377, in main
    mw.mm = PreferencesDialog(mw)
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan-master\morph\preferencesDialog.py", line 30, in __init__
    self.createNoteFilterTab()
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan-master\morph\preferencesDialog.py", line 57, in createNoteFilterTab
    rowData = get_preference('Filter')
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan-master\morph\preferences.py", line 13, in get_preference
    return _get_config_py_preference(key, model_id, deck_id)
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\MorphMan-master\morph\preferences.py", line 39, in _get_config_py_preference
    assert config_py, 'Tried to use cfgMods before profile loaded'
AssertionError: Tried to use cfgMods before profile loaded

**Comment by Geniusssmit** [comment]
On 3rd new profile without cards morphman is working just fine. need help
