### ISSUE TITLE
[BUG] Upcoming issues with the new 2.1.22 beta

### ISSUE THREAD

**Issue by kanjieater** [kaegi/MorphMan#97]
2.1.21 has issues with audio so I'm forced to use the 22beta. However morphman is incompatible. I understand it's probably not a high priority to support a beta release, but inevitably this will break for all users so it might be worth it to get ahead of the release. Details can be seen here: https://anki.tenderapp.com/discussions/ankidesktop/39307-2120-cards-stop-reproducing-sound-after-some-reviews

Reproduction steps:
1. Use the beta (22) from the link above
2. Open anki when morphman is present
3. See error:
```
Debug info:

Traceback (most recent call last):

File "aqt/main.py", line 441, in loadCollection

File "aqt/main.py", line 467, in _loadCollection

File "aqt/main.py", line 588, in moveToState

File "aqt/main.py", line 595, in _deckBrowserState

File "aqt/deckbrowser.py", line 66, in show

File "aqt/toolbar.py", line 48, in draw

File
"</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-24>",
line 2, in cs_toolbarCenterLinks

File "anki/hooks.py", line 666, in decorator_wrapper

File "anki/hooks.py", line 663, in repl

File "/Users/dmg/Library/Application
Support/Anki2/addons21/900801631/morph/stats.py", line 73, in my_centerLinks

return self._linkHTML(links)

AttributeError: 'Toolbar' object has no attribute '_linkHTML'
```

**Comment by glutanimate** [comment]
This is the change that introduced the incompatibility: https://github.com/ankitects/anki/pull/448

Sorry, @MorphMan devs, meant to ping you after submitting the PR and doing a quick search on which add-ons might be affected, but forgot about in the midst of other work

**Comment by shanrauf** [comment]
That's alright, thanks for letting us know. I'll work on fixing this soon.

**Comment by yiufung** [comment]
@kanjieater What a coincidence we bump into the same issues these days :) I just wrote a patch, feel free to try it out.

**Comment by edoreld** [comment]
I'm experiencing what appears to be the same problem on the recently released Anki 2.1.23:

<img width="532" alt="Screenshot 2020-03-19 at 15 28 18" src="https://user-images.githubusercontent.com/973854/77078307-b05d5780-69f6-11ea-9871-71e3fc0207d4.png">

**Comment by yiufung** [comment]
@edoreld Looks like the same issue. You may try my patch by modifying `stats.py` manually. It may take a while before MorphMan is updated in AnkiWeb.

**Comment by kanjieater** [comment]
Patch fixed 2.1.22 for me. Thanks!

**Comment by edoreld** [comment]
Patch fixed 2.1.23 for me :-)

**Comment by malxsant** [comment]
Sorry non-coder here. What should I replace in the stats.py in order for the add-on to work for 2.1.23? I have tried replacing the lines from the yiufung's patch but it doesn't seem to work, or I replaced them incorrectly. Attached are screenshots.

<img width="532" alt="Screen Shot 2020-03-19 at 11 06 25 AM" src="https://user-images.githubusercontent.com/18519679/77099937-0075f300-69d2-11ea-91c0-7e2b3333a738.png">

<img width="1680" alt="Screen Shot 2020-03-19 at 11 09 13 AM" src="https://user-images.githubusercontent.com/18519679/77100028-269b9300-69d2-11ea-9085-f0e91690feac.png">

<img width="1680" alt="Screen Shot 2020-03-19 at 11 09 16 AM" src="https://user-images.githubusercontent.com/18519679/77100039-2d2a0a80-69d2-11ea-96f4-d39e84d19299.png">

**Comment by yiufung** [comment]
@malxsant At line 68, please delete the spaces before "def on_top_toolbar_did_init_links". Python is an indentation-sensitive language, so spaces matter.

**Comment by Dhruv-Python** [comment]
Hey I tried adding the patch but it gave me this error: 
![image](https://user-images.githubusercontent.com/59411426/77756790-e1243900-7055-11ea-877b-3f269f054662.png)

This is what the file looks like:
![image](https://user-images.githubusercontent.com/59411426/77756874-16c92200-7056-11ea-83a6-58a0fd792861.png)
![image](https://user-images.githubusercontent.com/59411426/77756891-22b4e400-7056-11ea-822a-ba1d21e0c231.png)
![image](https://user-images.githubusercontent.com/59411426/77756950-3fe9b280-7056-11ea-9271-af7aaab6a6c5.png)
